# Generated by Django 5.2.3 on 2025-06-27 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cittadino',
            fields=[
                ('cssn', models.CharField(db_column='CSSN', max_length=16, primary_key=True, serialize=False, verbose_name='CSSN')),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=50, null=True, verbose_name='Nome')),
                ('cognome', models.CharField(blank=True, db_column='Cognome', max_length=50, null=True, verbose_name='Cognome')),
                ('indirizzo', models.CharField(blank=True, db_column='Indirizzo', max_length=100, null=True, verbose_name='Indirizzo')),
                ('numero_civico', models.IntegerField(blank=True, db_column='NumeroCivico', null=True, verbose_name='Numero Civico')),
                ('luogo_nascita', models.CharField(blank=True, db_column='LuogoNascita', max_length=100, null=True, verbose_name='Luogo di Nascita')),
                ('data_nascita', models.DateField(blank=True, db_column='DataNascita', null=True, verbose_name='Data di Nascita')),
            ],
            options={
                'verbose_name': 'Cittadino',
                'verbose_name_plural': 'Cittadini',
                'db_table': 'Cittadini',
                'ordering': ['cognome', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Patologia',
            fields=[
                ('id_patologia', models.AutoField(db_column='IDPatologia', primary_key=True, serialize=False)),
                ('nome_patologia', models.CharField(blank=True, db_column='NomePatologia', max_length=200, null=True, verbose_name='Nome Patologia')),
                ('tipologia', models.CharField(blank=True, db_column='Tipologia', max_length=50, null=True, verbose_name='Tipologia')),
            ],
            options={
                'verbose_name': 'Patologia',
                'verbose_name_plural': 'Patologie',
                'db_table': 'Patologie',
                'ordering': ['nome_patologia'],
            },
        ),
        migrations.CreateModel(
            name='Ospedale',
            fields=[
                ('id_ospedale', models.AutoField(db_column='IDOspedale', primary_key=True, serialize=False)),
                ('nome_ospedale', models.CharField(blank=True, db_column='NomeOspedale', max_length=100, null=True, verbose_name='Nome Ospedale')),
                ('indirizzo', models.CharField(blank=True, db_column='Indirizzo', max_length=100, null=True, verbose_name='Indirizzo')),
                ('numero_civico', models.IntegerField(blank=True, db_column='NumeroCivico', null=True, verbose_name='Numero Civico')),
                ('citta', models.CharField(blank=True, db_column='Citta', max_length=100, null=True, verbose_name='Città')),
                ('numero_telefono', models.CharField(blank=True, db_column='NumeroTelefono', max_length=20, null=True, verbose_name='Numero Telefono')),
                ('codice_sanitario_direttore', models.OneToOneField(blank=True, db_column='CodiceSanitarioDirettore', null=True, on_delete=django.db.models.deletion.PROTECT, to='hospital.cittadino', verbose_name='Direttore Sanitario')),
            ],
            options={
                'verbose_name': 'Ospedale',
                'verbose_name_plural': 'Ospedali',
                'db_table': 'Ospedali',
                'ordering': ['nome_ospedale'],
            },
        ),
        migrations.CreateModel(
            name='Ricovero',
            fields=[
                ('id_ricovero', models.AutoField(db_column='IDRicovero', primary_key=True, serialize=False)),
                ('data_ricovero', models.DateField(blank=True, db_column='DataRicovero', null=True, verbose_name='Data Ricovero')),
                ('durata_ricovero', models.IntegerField(blank=True, db_column='DurataRicovero', null=True, verbose_name='Durata Ricovero (giorni)')),
                ('costo_ricovero', models.DecimalField(blank=True, db_column='CostoRicovero', decimal_places=2, max_digits=10, null=True, verbose_name='Costo Ricovero (€)')),
                ('motivo_ricovero', models.CharField(blank=True, db_column='MotivoRicovero', max_length=255, null=True, verbose_name='Motivo Ricovero')),
                ('cittadino', models.ForeignKey(blank=True, db_column='CSSNCittadino', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hospital.cittadino', verbose_name='Cittadino')),
                ('ospedale', models.ForeignKey(db_column='IDOspedale', on_delete=django.db.models.deletion.CASCADE, to='hospital.ospedale', verbose_name='Ospedale')),
            ],
            options={
                'verbose_name': 'Ricovero',
                'verbose_name_plural': 'Ricoveri',
                'db_table': 'Ricoveri',
                'ordering': ['-data_ricovero'],
            },
        ),
        migrations.CreateModel(
            name='RicoveroPatologie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patologia', models.ForeignKey(db_column='IDPatologia', on_delete=django.db.models.deletion.CASCADE, to='hospital.patologia')),
                ('ricovero', models.ForeignKey(db_column='IDRicovero', on_delete=django.db.models.deletion.CASCADE, to='hospital.ricovero')),
            ],
            options={
                'verbose_name': 'Relazione Ricovero-Patologia',
                'verbose_name_plural': 'Relazioni Ricovero-Patologie',
                'db_table': 'Ricovero_Patologie',
                'unique_together': {('ricovero', 'patologia')},
            },
        ),
        migrations.AddField(
            model_name='ricovero',
            name='patologie',
            field=models.ManyToManyField(related_name='ricoveri', through='hospital.RicoveroPatologie', to='hospital.patologia', verbose_name='Patologie'),
        ),
    ]
